# Generated by Django 3.0.4 on 2020-10-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='past_course_strength',
            field=models.IntegerField(null=True),
        ),
    ]
