# Generated by Django 3.0.4 on 2020-12-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsettings',
            name='disable_all_courses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='ic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='course_load.Instructor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sem',
            field=models.CharField(choices=[('sem1', 'Odd'), ('sem2', 'Even'), ('sem12', 'Both')], default='sem12', max_length=5),
        ),
    ]
