# Generated by Django 3.0.4 on 2021-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='course_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instructor_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
