# Generated by Django 3.0.4 on 2020-11-06 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0002_remove_coursehistory_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
