# Generated by Django 3.0.4 on 2020-10-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_load', '0002_auto_20201007_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='past_course_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
